steps:
  # 依存関係をインストール
  - id: yarn-install
    name: node
    entrypoint: yarn
    args: ["install"]
  
  # Prismaマイグレーション
  - id: prisma-migration
    name: node
    entrypoint: sh
    args:
      - "-c"
      - |
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod 777 cloud_sql_proxy
        ./cloud_sql_proxy -instances=$$SQL_CONNECTIONNAME=tcp:3306 & sleep 3
        export SQL_DATABASE_URL=mysql://$$SQL_USERNAME:$$SQL_PASSWORD@127.0.0.1:3306/$$SQL_DATABASE
        yarn prisma migrate deploy
    secretEnv: ['SQL_CONNECTIONNAME','SQL_USERNAME','SQL_PASSWORD','SQL_DATABASE']
    waitFor: ["yarn-install"]

  # アプリケーションをビルド、フロントエンド側の環境変数セット
  - id: yarn-build
    name: node
    entrypoint: yarn
    args: ["build"]
    # Cloudbuildのダッシュボードにて環境変数設定したものをセット
    env:
     - NEXT_PUBLIC_SITE_URL=${_SITE_URL}
     - NEXT_PUBLIC_GOOGLE_ANALYTICS=${_GOOGLE_ANALYTICS}
     - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${_RECAPTCHA_SITE_KEY}
     - GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}
     - ENVIRONMENT=${_ENVIRONMENT}

  # アプリケーションをデプロイ、ProdとStatingによりデプロイ環境変更
  - id: deploy
    name: gcr.io/cloud-builders/gcloud
    args: ["app", "deploy", "app.${BRANCH_NAME}.yaml", "--project=${PROJECT_ID}", "--quiet"]

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/PROD_SQL_CONNECTIONNAME/versions/latest
    env: 'SQL_CONNECTIONNAME'
  - versionName: projects/$PROJECT_ID/secrets/PROD_SQL_USERNAME/versions/latest
    env: 'SQL_USERNAME'
  - versionName: projects/$PROJECT_ID/secrets/PROD_SQL_PASSWORD/versions/latest
    env: 'SQL_PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/PROD_SQL_DATABASE/versions/latest
    env: 'SQL_DATABASE'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1000s"
